"""base

Revision ID: 6a444801c6aa
Revises: 
Create Date: 2023-01-22 03:19:07.037742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a444801c6aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_definition',
    sa.Column('data_def_id', sa.Integer(), nullable=False),
    sa.Column('data_endpoint', sa.String(), nullable=True),
    sa.Column('data_method', sa.String(), nullable=True),
    sa.Column('data_schema', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('data_def_id')
    )
    op.create_table('data_ingest_records',
    sa.Column('data_ing_id', sa.Integer(), nullable=False),
    sa.Column('data_ingest', sa.String(), nullable=True),
    sa.Column('data_def_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_def_id'], ['data_definition.data_def_id'], ),
    sa.PrimaryKeyConstraint('data_ing_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_ingest_records')
    op.drop_table('data_definition')
    # ### end Alembic commands ###
