"""created time ingest

Revision ID: 7a532607cabd
Revises: 6a444801c6aa
Create Date: 2023-01-22 15:57:04.249588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a532607cabd'
down_revision = '6a444801c6aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_ingest_records', sa.Column('created_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_ingest_records', 'created_time')
    # ### end Alembic commands ###
